// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328160000_AddCommentReplies")]
    partial class AddCommentReplies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
